name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Creer fichier .env
        run: |
          echo "FLASK_PORT=${{ secrets.FLASK_PORT }}" >> .env
          echo "API_GATEWAY_URL=${{ secrets.API_GATEWAY_URL }}" >> .env

      # - name: Run tests
      #   working-directory: src
      #   run: echo "Call pytest command here!"
